name: Deploy PRD Porto

description: Deploy PRD Porto

inputs:
  GITHUB_TOKEN:
    required: true
    description: Github Token
  DEPLOY_TO:
    required: true
    description: Set Enviroment to deploy
  SSH_PRIV_KEY_LIBS_BACKEND:
    required: true
    description: SSH_PRIV_KEY_LIBS_BACKEND

runs:
  using: "composite"
  steps:
    - name: Change Owner of Container Working Directory
      run: chown -R $(id -u):$(id -g) $PWD
      shell: bash
      
    - name: Checkout Main
      uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Get latest release
      id: latest_release
      uses: kaliber5/action-get-release@v1
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        latest: true

    - name: Get Version to Deploy
      run: echo "TAG=${{ steps.latest_release.outputs.tag_name }}" >> $GITHUB_ENV
      shell: bash

    - name: Upgrade wheel, setuptools, virtualenv
      run: python2 --version; python2 -m pip install --upgrade pip wheel setuptools virtualenv
      shell: bash
    
    - name: Get SSH_KEY LIBS-BACKEND
      run: echo "${{inputs.SSH_PRIV_KEY_LIBS_BACKEND}}" > ssh-rsa.key ; atar-cli deploy --set-ssh=ssh-rsa.key ; rm -f ssh-rsa.key
      shell: bash
    
    - name: Update Client/Update Third Party
      run: atar-cli --update-all
      shell: bash

    - name: Deploy AppEngine ${{github.event.repository.name}} - ${{env.TAG}}
      run: |

      shell: bash

    - name: Check Promote and GAE Deploy ${{github.event.repository.name}} - ${{env.TAG}}
      run: |
        if [[ (${{ inputs.DEPLOY_TO }} == 'app.yaml') ]]
        then
            echo $PORTO_CREDENTIALS|gcloud auth activate-service-account --key-file=-
            OLD_TAG=${{env.TAG}}
            TAG="${OLD_TAG//./-}"
            ${RETRY} gcloud -q --project=${PORTO_PROJECT} app deploy app.yaml -v=$TAG --promote
        elif [[ (${{ inputs.DEPLOY_TO }} == 'app-prod-porto.yaml') ]]
        then
            echo $PORTO_CREDENTIALS|gcloud auth activate-service-account --key-file=-
            OLD_TAG=${{env.TAG}}
            TAG="${OLD_TAG//./-}"
            ${RETRY} gcloud -q --project=${PORTO_PROJECT} app deploy app.prod-porto.yaml -v=$TAG --promote
        fi
      shell: bash